### ISSUE TITLE
[Bug]Using the env-vars command froze

### ISSUE THREAD

**Issue by motikan2010** [BishopFox/cloudfox#13]
- % of customers impacted: [100]%
- Affected Users: [Engineers / Operators / Customers]
- Is revenue impacted: [Yes / No]
- Urgency: [High / Medium / Low]
- Deadline: [Date]

## Description of Bug

I used the `env-vars` command and it froze.

```
❯ ./cloudfox aws env-vars --profile reader-admin-hoge
[🦊 cloudfox v1.7.1 🦊 ] AWS Caller Identity: arn:aws:iam::364399834359:user/reader-admin
[env-vars] Enumerating environment variables in all regions for account 364399834359.
[env-vars] Supported Services: App Runner, Elastic Container Service, Lambda, Lightsail Containers, Sagemaker
[env-vars] Status: 0/105 tasks complete (0 errors -- For details check /Users/motikan2010/.cloudfox/cloudfox-error.log)
(...freeze..)
```

## What should the expected behavior be

- Command completed.
- Result files (`table/env-vars.txt`, `csv/env-vars.csv`) are output successfully.

## Platform Affected
[ ] Dev
[ ] Preview
[ ] Production

## Steps to Reproduce

Run `aws env-vars` command.

ex. `./cloudfox aws env-vars`

### Additional context

The `Goroutines` argument is required, but was not passed.
In my environment, the following modifications made it work correctly.

```
❯ git diff
diff --git a/cli/aws.go b/cli/aws.go
index 662485f..2a45ea7 100644
--- a/cli/aws.go
+++ b/cli/aws.go
@@ -480,6 +480,7 @@ var (
                                        Caller:          *caller,
                                        AWSRegions:      AWSRegions,
                                        AWSProfile:      profile,
+                                       Goroutines:      Goroutines,
                                        ECSClient:       ecs.NewFromConfig(AWSConfig),
                                        AppRunnerClient: apprunner.NewFromConfig(AWSConfig),
                                        LambdaClient:    lambda.NewFromConfig(AWSConfig),
```

Golang version
```
$ go version
go version go1.17.6 darwin/amd64
```

**Comment by sethsec-bf** [comment]
Thanks so much for catching this @motikan2010. This has been merged into main and is reflected in release v1.7.2
