### ISSUE TITLE
List on Homebrew for easier installation and regular updates

### ISSUE THREAD

**Issue by wilcosec** [BishopFox/cloudfox#47]
As a security professional,
I want to install CloudFox using [Homebrew](https://brew.sh/) 
so that installation and updating is as easy as possible. 

## Overview
Homebrew is a well-known package manager for MacOS and Linux, which allows single command installations of packages (called Formula) and single command updating. 

CloudFox meets all [requirements](https://docs.brew.sh/Acceptable-Formulae) to be listed as a Formula in Homebrew. I feel like listing on Homebrew will lower the barrier of entry (and of keeping up to date) for many security professionals. 

Listing CloudFox as a formula in Homebrew should be easy, but I've never done it, so I can't speak from first-hand experience.

## Acceptance Criteria
- [ ] Security implications approved.
- [ ] CloudFox is installable on MacOS with `brew install cloudfox`.

#### Non Functional Requirements/Wants
- [ ] Ideally, the Homebrew formula for CloudFox is updated with the latest version numbers via CI from this project.

#### External Documents / Links
* Homebrew home page: https://brew.sh/
* Acceptable formulae guide: https://docs.brew.sh/Acceptable-Formulae
* Overview to creating a formula: https://docs.brew.sh/Adding-Software-to-Homebrew
* Detailed formula reference: https://docs.brew.sh/Formula-Cookbook

**Comment by sethsec-bf** [comment]
Thanks for this issue @wilcosec! This is definitely on my todo list and I appreciate you putting this issue together with some guidance!

**Comment by sethsec-bf** [comment]
CloudFox is now in Brew!  Thanks for the push @wilcosec.  The final piece i need to figure out is how to configure an action on my end to auto bump the brew Forumula every time i release a new cloudfox version.

**Comment by sethsec-bf** [comment]
Thank you so much for your offer @tmendonca28! That all sounds amazing and it would be appreciated.  Funny you should ask about a version file. @bishopfaure has implemented a version file within his Azure related PR #60 here: https://github.com/BishopFox/cloudfox/pull/60/files#diff-f60cb3972288e96bfc533c53faac95c27921093863611596b068494ef850ff2e. So as soon as that lands in main we will have that.  

Let me sync with @bishopfaure on how close that is to being ready to merge and I'll update you on. Thanks again!!

**Comment by tmendonca28** [comment]
Awesome! That's perfect then 😃  - looking forward to hearing from you on when https://github.com/BishopFox/cloudfox/pull/60 is merged. 

I will get to work pre-emptively since I know where the version file will be located and what it entails.

**Comment by sethsec-bf** [comment]
Hey @tmendonca28 - It might take a bit longer for me and @bishopfaure to sync up on our end. I'm good with either of your approaches, and honestly, would love to lean on your opinions on what you think is best moving forward.  As noted above, in pull #60 you can see the plan for a version file. Feel free to just add that new file to your new PR ahead of that PR being merged and go that route if you like.  Or you can add it to the action that exists that is triggered whenever i push a new version tag as you suggested. 

The only other piece you might need is where I am am currently tracking the version in the code. It's in main.go :) https://github.com/BishopFox/cloudfox/blob/main/main.go#L13.  

I have a few bug fixes ready in `seth-dev` and i've changed the version in main.go to 1.12.3, so when you get this in we can use 1.12.3 release to test your homebrew updates.

thanks again!

**Comment by sethsec-bf** [comment]
Hey @tmendonca28  - Homebrew seems to be getting my release updates and making new brew formulas. Not sure why or how, but i think we can close this issue out now. Thanks again for your offer to help! if you can figure out how it is working, feel free to let me know :) 

https://github.com/Homebrew/homebrew-core/pull/158318

**Comment by tmendonca28** [comment]
Hey @sethsec-bf  - Pardon me for the late response, had taken a bit of a digital detox during the festive season. Let me have a look as to how/why it's getting the release updates and will revert asap 😃
